/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;

import com.alee.laf.WebLookAndFeel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import pilgrimscrutinizer.DBOperation;
import pilgrimscrutinizer.customerdetails;

/**
 *
 * @author Sachithra
 */
public class addcustomer1 extends javax.swing.JFrame {

    /**
     * Creates new form addcustomer1
     */
    public addcustomer1() {
        initComponents();
        db.rettourlist(ddtours);
        try {
            UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (Exception e) {
            System.out.println("Couldn't load Mac L&F" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        panelpersonaldetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcsurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ddgender = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        rbmarried = new javax.swing.JRadioButton();
        rbsingle = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ddyear = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        ddmonth = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        dddate = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtcnicno = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtinitial = new javax.swing.JTextField();
        Panelpassdetail = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtcpassportno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpassissuedate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpassissueplace = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpassexpdate = new javax.swing.JTextField();
        btnbackpass = new javax.swing.JButton();
        btnnextpass = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcurraddres = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpermanentaddress = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtmobno = new javax.swing.JTextField();
        jl = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnbackcontact = new javax.swing.JButton();
        btnnextcontact = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtpayment = new javax.swing.JTextField();
        ddtours = new javax.swing.JComboBox();
        btnbacktour = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        panelpersonaldetail.setBackground(new java.awt.Color(255, 255, 255));
        panelpersonaldetail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Customer full name");

        txtcname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Surname");

        txtcsurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Gender");

        ddgender.setBackground(new java.awt.Color(204, 204, 255));
        ddgender.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ddgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "female" }));
        ddgender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Marital Status");

        rbmarried.setBackground(new java.awt.Color(204, 204, 255));
        rbmarried.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbmarried.setText("Married");
        rbmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmarriedActionPerformed(evt);
            }
        });

        rbsingle.setBackground(new java.awt.Color(204, 204, 255));
        rbsingle.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbsingle.setText("Single");
        rbsingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsingleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Date Of Birth");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Year :");

        ddyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", " ", " " }));
        ddyear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ddyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddyearActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Month :");

        ddmonth.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ddmonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "June", "July", "August", "September", "October", "November", "December" }));
        ddmonth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Date :");

        dddate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dddate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("NIC No");

        txtcnicno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnnext.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Nationality");

        txtnationality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("Initials");

        txtinitial.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtinitial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelpersonaldetailLayout = new javax.swing.GroupLayout(panelpersonaldetail);
        panelpersonaldetail.setLayout(panelpersonaldetailLayout);
        panelpersonaldetailLayout.setHorizontalGroup(
            panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel18))
                                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtnationality, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                                .addComponent(txtcnicno, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ddyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ddmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                                                .addComponent(rbmarried)
                                                .addGap(66, 66, 66)
                                                .addComponent(rbsingle))
                                            .addComponent(ddgender, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtinitial, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        panelpersonaldetailLayout.setVerticalGroup(
            panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpersonaldetailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtinitial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpersonaldetailLayout.createSequentialGroup()
                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ddgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbmarried)
                            .addComponent(rbsingle)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel19)
                            .addComponent(ddyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(ddmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(dddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcnicno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpersonaldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addGap(95, 95, 95)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Personal Details", panelpersonaldetail);

        Panelpassdetail.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Passport No");

        txtcpassportno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtcpassportno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Date Of Issue");

        txtpassissuedate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtpassissuedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Place Of Issue");

        txtpassissueplace.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtpassissueplace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("Date Of Expiry");

        txtpassexpdate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtpassexpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnbackpass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnbackpass.setText("BACK");
        btnbackpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackpassActionPerformed(evt);
            }
        });

        btnnextpass.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnnextpass.setText("NEXT");
        btnnextpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelpassdetailLayout = new javax.swing.GroupLayout(Panelpassdetail);
        Panelpassdetail.setLayout(PanelpassdetailLayout);
        PanelpassdetailLayout.setHorizontalGroup(
            PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelpassdetailLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpassissuedate)
                    .addComponent(txtpassissueplace)
                    .addComponent(txtpassexpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txtcpassportno))
                .addContainerGap(362, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelpassdetailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbackpass, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnnextpass, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        PanelpassdetailLayout.setVerticalGroup(
            PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelpassdetailLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcpassportno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassissueplace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassexpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(PanelpassdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnextpass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbackpass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
        );

        jTabbedPane4.addTab("Passport Details", Panelpassdetail);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("Current Address");

        txtcurraddres.setColumns(20);
        txtcurraddres.setRows(5);
        txtcurraddres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtcurraddres);

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("Permanent Address");

        txtpermanentaddress.setColumns(20);
        txtpermanentaddress.setRows(5);
        txtpermanentaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtpermanentaddress);

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setText("Phone No");

        txtphoneno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtphoneno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Mobile Phone No");

        txtmobno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtmobno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jl.setText("Email Address");

        txtemail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtemail.setToolTipText("");
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnbackcontact.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnbackcontact.setText("BACK");
        btnbackcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackcontactActionPerformed(evt);
            }
        });

        btnnextcontact.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnnextcontact.setText("NEXT");
        btnnextcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextcontactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jl))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtemail)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(txtphoneno))
                    .addComponent(txtmobno, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbackcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnnextcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtmobno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnextcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbackcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Contact Details", jPanel6);

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("Tour ");

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("Payment");

        txtpayment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtpayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ddtours.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ddtours.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnbacktour.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnbacktour.setText("BACK");
        btnbacktour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacktourActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpayment, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(ddtours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(264, 264, 264))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbacktour, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnsubmit)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ddtours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbacktour, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jTabbedPane4.addTab("Tour Details", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DBOperation db=new DBOperation();
    private void rbmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmarriedActionPerformed
        // TODO add your handling code here:
        if (rbmarried.isSelected()) {
            rbsingle.setSelected(false);
        }
    }//GEN-LAST:event_rbmarriedActionPerformed

    private void rbsingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsingleActionPerformed
        // TODO add your handling code here:
        if (rbsingle.isSelected()) {
            rbmarried.setSelected(false);
        } else {
        }
    }//GEN-LAST:event_rbsingleActionPerformed

    private void ddyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddyearActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        jTabbedPane4.setSelectedIndex(1);
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnbackpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackpassActionPerformed
        // TODO add your handling code here:
        jTabbedPane4.setSelectedIndex(0);
    }//GEN-LAST:event_btnbackpassActionPerformed

    private void btnnextpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextpassActionPerformed
        // TODO add your handling code here:
        jTabbedPane4.setSelectedIndex(2);
    }//GEN-LAST:event_btnnextpassActionPerformed

    private void btnbackcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackcontactActionPerformed
        // TODO add your handling code here:
        jTabbedPane4.setSelectedIndex(1);
    }//GEN-LAST:event_btnbackcontactActionPerformed

    private void btnnextcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextcontactActionPerformed
        // TODO add your handling code here:
        jTabbedPane4.setSelectedIndex(3);
    }//GEN-LAST:event_btnnextcontactActionPerformed

    private void btnbacktourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacktourActionPerformed
        // TODO add your handling code here:
        jTabbedPane4.setSelectedIndex(2);
    }//GEN-LAST:event_btnbacktourActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        //db.retTourList(ddtours);
        if (checkfields()) {
            JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(btnsubmit), "some fields not filled..!!");
        } else {
            try {
                customerdetails cd = new customerdetails();
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = new Date();
                String currentdate = dateFormat.format(date);
                cd.setCurrentaddress(txtcurraddres.getText());
                if (rbmarried.isSelected() && ddgender.getSelectedItem().equals("female")) {
                    cd.setCivilstatus("MRs");
                } else if (rbsingle.isSelected() && ddgender.getSelectedItem().equals("female")) {
                    cd.setCivilstatus("MS");
                } else {
                    cd.setCivilstatus("MR");
                }
                cd.setCustaddeddate(date);
                String dob = ddyear.getSelectedItem().toString() + ddmonth.getSelectedItem().toString() + dddate.getSelectedItem().toString();
                cd.setDateofbirth(dob);
                cd.setEmailaddress(txtemail.getText());
                cd.setGender(ddgender.getSelectedItem().toString());
                cd.setInitials(txtinitial.getText());
                if (rbmarried.isSelected()) {
                    cd.setMaritalstatus(rbmarried.getText());
                } else {
                    cd.setMaritalstatus(rbsingle.getText());
                }
                cd.setMobileno(Integer.parseInt(txtmobno.getText()));
                cd.setName(txtcname.getText());
                cd.setNationality(txtnationality.getText());
                cd.setNicno(txtcnicno.getText());
                cd.setPassportexpdate(txtpassexpdate.getText());
                cd.setPassportissuedate(txtpassissuedate.getText());
                cd.setPassportissueplace(txtpassissueplace.getText());
                cd.setPassportno(txtcpassportno.getText());
                cd.setPayment(Integer.parseInt(txtpayment.getText()));
                cd.setPermanaddress(txtpermanentaddress.getText());
                cd.setPhoneno(Integer.parseInt(txtphoneno.getText()));
                cd.setSurname(txtcsurname.getText());
                cd.setTour(ddtours.getSelectedItem().toString());
                cd.setTourid(Integer.parseInt(ddtours.getSelectedItem().toString().substring(0, 1)));
                cd.setCustid(0);
                boolean result = db.addcustomer(cd);
                if (result) {
                    JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(btnsubmit), "Data entered successfully..!!");
                } else {
                    JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(btnsubmit), "Error occured..!!");
                }
            } catch (Exception e) {
                System.out.print(e);
            }
        }

    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcustomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcustomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcustomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcustomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcustomer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelpassdetail;
    private javax.swing.JButton btnbackcontact;
    private javax.swing.JButton btnbackpass;
    private javax.swing.JButton btnbacktour;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnnextcontact;
    private javax.swing.JButton btnnextpass;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox dddate;
    private javax.swing.JComboBox ddgender;
    private javax.swing.JComboBox ddmonth;
    private javax.swing.JComboBox ddtours;
    private javax.swing.JComboBox ddyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel jl;
    private javax.swing.JPanel panelpersonaldetail;
    private javax.swing.JRadioButton rbmarried;
    private javax.swing.JRadioButton rbsingle;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtcnicno;
    private javax.swing.JTextField txtcpassportno;
    private javax.swing.JTextField txtcsurname;
    private javax.swing.JTextArea txtcurraddres;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtinitial;
    private javax.swing.JTextField txtmobno;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtpassexpdate;
    private javax.swing.JTextField txtpassissuedate;
    private javax.swing.JTextField txtpassissueplace;
    private javax.swing.JTextField txtpayment;
    private javax.swing.JTextArea txtpermanentaddress;
    private javax.swing.JTextField txtphoneno;
    // End of variables declaration//GEN-END:variables

    public boolean checkfields() {
        if (txtcname.getText().isEmpty() | txtcnicno.getText().isEmpty() | txtcpassportno.getText().isEmpty() | txtcsurname.getText().isEmpty()
                | txtcurraddres.getText().isEmpty() | txtemail.getText().isEmpty() | txtinitial.getText().isEmpty() | txtmobno.getText().isEmpty()
                | txtnationality.getText().isEmpty() | txtpassexpdate.getText().isEmpty() | txtpassissuedate.getText().isEmpty()
                | txtpassissueplace.getText().isEmpty() | txtpayment.getText().isEmpty() | txtpermanentaddress.getText().isEmpty() | txtphoneno.getText().isEmpty()) {
            return true;

        } else {
            return false;
        }
    }
}
